export const GET_HOMEPAGE = "GET_HOMEPAGE";
export const HOMEPAGE_ERROR = "HOMEPAGE_ERROR";
export const GET_BY_ID_HOMEPAGE = "GET_BY_ID_HOMEPAGE";
export const ADD_HOMEPAGE = "ADD_HOMEPAGE";
export const EDIT_HOMEPAGE = "EDIT_HOMEPAGE";
export const DELETE_HOMEPAGE = "DELETE_HOMEPAGE";

export const GET_USERS = "GET_USERS";
export const ADD_USERS = "ADD_USERS";
export const EDIT_USERS = "EDIT_USERS";
export const DELETE_USERS = "DELETE_USERS";
export const USERS_ERROR = "USERS_ERROR";

export const LOGIN_ADMIN = "LOGIN_ADMIN";
export const LOGIN_USERS = "LOGIN_USERS";
export const LOGIN_ERROR = "LOGIN_ERROR";

export const GET_LEADERBOARD = "GET_LEADERBOARD";
export const LEADERBOARD_ERROR = "LEADERBOARD_ERROR";

export const GET_PRODUCTS = "GET_PRODUCTS";
export const PRODUCTS_ERROR = "PRODUCTS_ERROR";
export const GET_BY_ID_PRODUCTS = "GET_BY_ID_PRODUCTS";
export const ADD_PRODUCTS = "ADD_PRODUCTS";
export const EDIT_PRODUCTS = "EDIT_PRODUCTS";
export const DELETE_PRODUCTS = "DELETE_PRODUCTS";
