import { useEffect } from "react";
import { useDispatch, useSelector } from "react-redux";
import { useRouter } from "next/router";
import { getById } from "../../redux/action/productAction";
import styled from "styled-components";
import React from "react";
import ProductImage from "../../components/ProductDetail/ProductImage";
import GeneralDetails from "../../components/ProductDetail/GeneralDetails";
import Purchase from "../../components/ProductDetail/Purchase";
import ItemActivity from "../../components/ProductDetail/ItemActivity";
import Image from "next/image";
import Link from "next/link";
import Header from "../../components/Header";
import "../../GlobalVariable";
import BuyButton from "../../components/ProductDetail/BuyButton";
import ProductDetails from "../../components/ProductDetail/ProductDetail";
import Head from "next/head";

const ProductDetail = () => {
  const dispatch = useDispatch();
  const allProductsData = useSelector((state) => state.Products);
  const { loading, error, product } = allProductsData;
  const router = useRouter();
  const { id } = router.query;
  // LOAD DATA
  useEffect(() => {
    if (router.isReady) {
      // Code using query
      dispatch(getById(id));
    }
  }, [id]);
  return (
    //
    <article className="AssetEl">
      <Head>
        <title>Detil Produk</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/boxicons@latest/css/boxicons.min.css"
        />
      </Head>
      <Header />
      <ProductDetails loading={loading} error={error} product={product} />
      <div className="itemActivity">
        <ItemActivity PA={product} />
      </div>
    </article>
  );
};
export default ProductDetail;
