import Head from "next/head";
import Link from "next/link";
import { Button } from "reactstrap";

function EditProfile() {
  return (
    <div>
      <Head>
        <title>Edit Profile</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/boxicons@latest/css/boxicons.min.css"
        />
      </Head>
      <header className="header" id="header">
        <nav className="nav container">
          <a href="https://nextjs.org">Batiqun</a>
          {/* <input
            id="quick_search"
            className="xs-hide style-2"
            name="quick_search"
            placeholder="search item here..."
            type="text"
          /> */}
          <div className="nav__menu" id="nav-menu">
            <ul className="nav__list">
              <li className="nav__item">
                <Link href="/">
                  <a className="nav__link">
                    <i className="bx bx-home-alt nav__icon"></i>
                    <span className="nav__name">Home</span>
                  </a>
                </Link>
              </li>
              <li className="nav__item">
                <Link href="/Leaderboards">
                  <a className="nav__link">
                    <i className="bx bx-bar-chart-alt-2 nav__icon"></i>
                    <span className="nav__item">Leaderboards</span>
                  </a>
                </Link>
              </li>
              <li className="nav__item">
                <Link href="/Profile">
                  <a className="nav__link active-link">
                    <i className="bx bx-user nav__icon"></i>
                    <span className="nav__item">Profile</span>
                  </a>
                </Link>
              </li>
            </ul>
          </div>
        </nav>
      </header>

      <main>
        <section className="pt-16">
          <div className="container-fluid py-1">
            <div className="row">
              <div className="col-lg-4">
                <div className="max-w-screen-lg rounded mt-3 overflow-hidden shadow-sm bg-[#fff]">
                  <div className="px-6 py-4 grid place-content-center">
                    <div className="font-bold text-xl mb-2">
                      Ubah Foto Profil
                    </div>
                    <img
                      className="rounded-full h-40 w-40 object-center"
                      src="../../profile.jpg"
                      alt="Sunset in the mountains"
                    />
                  </div>
                  <div className="px-6 pt-4 pb-2">
                    <div className="form-group">
                      <label className="form-control-label">
                        Upload Foto Profil
                      </label>
                      <input
                        type="file"
                        className="form-control"
                        placeholder="choose file"
                        name="file"
                        //   onChange={handleFile}
                        required
                      />
                    </div>
                  </div>
                </div>
                <div className="max-w-screen-lg rounded mt-3 overflow-hidden shadow-sm bg-[#fff]">
                  <div className="px-6 py-4 grid place-content-center">
                    <div className="font-bold text-xl mb-2 ">Ubah Header</div>
                    <img
                      className="rounded-full h-40 w-40 object-center"
                      src="../../profile.jpg"
                      alt="Sunset in the mountains"
                    />
                  </div>
                  <div className="px-6 pt-4 pb-2">
                    <div className="form-group">
                      <label className="form-control-label">
                        Upload Header
                      </label>
                      <input
                        type="file"
                        className="form-control"
                        placeholder="choose file"
                        name="file"
                        //   onChange={handleFile}
                        required
                      />
                    </div>
                  </div>
                </div>
              </div>

              <div className="col-lg-8">
                <div className="card mt-3">
                  <div className="card-header">
                    <div className="row align-items-center">
                      <div className="col-8">
                        <h3 className="mb-0">Edit profile </h3>
                      </div>
                    </div>
                  </div>

                  <div className="card-body">
                    <form>
                      <h6 className="heading-small text-muted mb-4">
                        User information
                      </h6>
                      <div className="pl-lg-4">
                        <div className="row">
                          <div className="col-lg-6">
                            <div className="form-group">
                              <label className="form-control-label">
                                Fullname
                              </label>
                              <input
                                type="input"
                                className="form-control"
                                placeholder="enter your name"
                                name="txtFullName"
                                required
                                //   onChange={handleChangeEdit}
                                //   value={userEdit.txtFullName}
                              />
                            </div>
                          </div>
                          <div className="col-lg-6">
                            <div className="form-group">
                              <label className="form-control-label">
                                Email Address
                              </label>
                              <input
                                type="email"
                                className="form-control"
                                placeholder="enter your email"
                                name="txtEmail"
                                //   required
                                //   onChange={handleChangeEdit}
                                //   value={userEdit.txtEmail}
                              />
                            </div>
                          </div>
                        </div>
                        <div className="row">
                          <div className="col-lg-6">
                            <div className="form-group">
                              <label className="form-control-label">
                                Password
                              </label>
                              <input
                                type="password"
                                className="form-control"
                                placeholder="enter password"
                                name="txtPassword"
                                required
                                //   onChange={handleChangeEdit}
                                //   value={userEdit.txtPassword}
                              />
                            </div>
                          </div>
                          <div className="col-lg-6">
                            <div className="form-group">
                              <label className="form-control-label">
                                Eth Address
                              </label>
                              <input
                                type="input"
                                className="form-control"
                                name="ethAddress"
                                //   onChange={handleChangeEdit}
                                //   value={userEdit.ethAddress}
                                disabled
                              />
                            </div>
                          </div>
                        </div>
                      </div>
                      <hr className="my-4" />
                      {/* <!-- Address --> */}
                      <h6 className="heading-small text-muted mb-4">
                        Contact information
                      </h6>
                      <div className="pl-lg-4">
                        <div className="row">
                          <div className="col-lg-4">
                            <div className="form-group">
                              <label className="form-control-label">
                                Twitter
                              </label>
                              <input
                                type="input"
                                className="form-control"
                                placeholder="@example"
                                name="twitter"
                                // onChange={handleChangeEdit}
                                //   value={user.Twitter}
                              />
                            </div>
                          </div>
                          <div className="col-lg-4">
                            <div className="form-group">
                              <label className="form-control-label">
                                Instagram
                              </label>
                              <input
                                type="input"
                                className="form-control"
                                placeholder="@example"
                                name="instagram"
                                // onChange={handleChangeEdit}
                                //   value={user.Instagram}
                              />
                            </div>
                          </div>
                          <div className="col-lg-4">
                            <div className="form-group">
                              <label className="form-control-label">
                                Website
                              </label>
                              <input
                                type="input"
                                className="form-control"
                                placeholder="www@example.id"
                                name="website"
                                // onChange={handleChangeEdit}
                                //   value={user.Website}
                              />
                            </div>
                          </div>
                        </div>
                      </div>
                      {/* <hr className="my-4" />
                <h6 className="heading-small text-muted mb-4">About me</h6> */}
                      <div className="pl-lg-4">
                        <div className="form-group">
                          <label className="form-control-label">About me</label>
                          <textarea
                            type="input"
                            className="form-control"
                            placeholder="write about you"
                            name="bio"
                            required
                            // onChange={handleChangeEdit}
                            //   value={userEdit.Bio}
                          />
                        </div>
                      </div>

                      {/* <Button
                      //   onClick={handleUpdate}
                      color="primary"
                      type="button"
                    >
                      Save changes
                    </Button> */}
                    </form>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
export default EditProfile;
