import Head from "next/head";
import Image from "next/image";
import styles from "../../styles/Home.module.css";
// import "../js/main.js";

const style = {
  bannerImageContainer: `h-64 w-screen overflow-hidden flex justify-center items-center`,
  bannerImage: `w-full object-cover`,
  infoContainer: `w-screen px-4`,
  midRow: `w-full flex justify-center text-black`,
  endRow: `w-full flex justify-end text-black`,
  profileImg: `w-40 h-40 object-cover rounded-full border-2 border-[#202225] mt-[-4rem]`,
  socialIconsContainer: `flex text-3xl mb-[-2rem]`,
  socialIconsWrapper: `w-32`,
  socialIconsContent: `flex container justify-around text-[1.4rem] border-2 rounded-lg px-2`,
  socialIcon: `my-2`,
  divider: `border-r-2`,
  title: `text-5xl font-bold mb-4`,
  createdBy: `text-lg mb-4`,
  statsContainer: `w-[78vw] flex justify-between py-4 border border-[#151b22] rounded-xl mb-4`,
  collectionStat: `w-1/4`,
  statValue: `text-3xl font-bold w-full flex items-center justify-center`,
  ethLogo: `h-6 mr-2`,
  statName: `text-lg w-full text-center mt-1`,
  description: `text-[#8a939b] text-xl w-max-1/4 flex-wrap mt-4`,
};
export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/boxicons@latest/css/boxicons.min.css"
        />
      </Head>

      <header className="header" id="header">
        <nav className="nav container">
          <a href="https://nextjs.org">Batiqun</a>
          {/* <input
            id="quick_search"
            className="xs-hide style-2"
            name="quick_search"
            placeholder="search item here..."
            type="text"
          /> */}
          <div className="nav__menu" id="nav-menu">
            <ul className="nav__list">
              <li className="nav__item">
                <a href="/" className="nav__link">
                  <i className="bx bx-home-alt nav__icon"></i>
                  <span className="nav__name">Home</span>
                </a>
              </li>
              <li className="nav__item">
                <a href="#leaderboards" className="nav__link">
                  <i className="bx bx-bar-chart-alt-2 nav__icon"></i>
                  <span className="nav__item">Leaderboards</span>
                </a>
              </li>
              <li className="nav__item">
                <a href="#profile" className="nav__link active-link">
                  <i className="bx bx-user nav__icon"></i>
                  <span className="nav__item">Profile</span>
                </a>
              </li>
            </ul>
          </div>
        </nav>
      </header>

      <main>
        {/* <section className="container section section__height" id="home"> */}
        {/* <div className="header-title">
            <h3>Connect your wallet.</h3>
          </div>
          <div className="text-center">
            <button type="button" className="btnConnect">
              <img src="image5.png" />
              Connect with Metamask
            </button>
          </div> */}
        <div className={style.bannerImageContainer}>
          <img className={style.bannerImage} src="bg.jpg" alt="banner" />
        </div>
        <div className={style.infoContainer}>
          <div className={style.midRow}>
            <img
              className={style.profileImg}
              src="profile.jpg"
              alt="profile image"
            />
          </div>
          <div className={style.endRow}>
            <div className={style.socialIconsContainer}>
              <div className={style.socialIconsWrapper}>
                <div className={style.socialIconsContent}>
                  <div className={style.socialIcon}>
                    <i className="fa-brands fa-instagram"></i>
                  </div>
                  <div className={style.divider} />
                  <div className={style.socialIcon}>
                    <i className="fa-brands fa-twitter"></i>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div className={style.midRow}>
            <div className={style.title}>adssa</div>
          </div>
          <div className={style.midRow}>
            <div className={style.createdBy}>TOKEN</div>
          </div>
          <div className={style.midRow}>
            <div className={style.statsContainer}>
              <div className={style.collectionStat}>
                <div className={style.statValue}>342</div>
                <div className={style.statName}>items</div>
              </div>
              <div className={style.collectionStat}>
                <div className={style.statValue}>213213</div>
                <div className={style.statName}>owners</div>
              </div>
              <div className={style.collectionStat}>
                <div className={style.statValue}>
                  <i className="fa-brands fa-ethereum"></i>
                  4241
                </div>
                <div className={style.statName}>floor price</div>
              </div>
              <div className={style.collectionStat}>
                <div className={style.statValue}>
                  <i className="fa-brands fa-ethereum"></i>
                  5K
                </div>
                <div className={style.statName}>volume traded</div>
              </div>
            </div>
          </div>
          <div className={style.midRow}>
            <div className={style.description}>assa</div>
          </div>
        </div>

        {/* </section> */}
      </main>
    </div>
  );
}
