import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useEffect } from "react";
import { useDispatch, useSelector } from "react-redux";
import { getHomepage } from "../redux/action/homepageAction";
import styles from "../styles/Home.module.css";
import KaryaCard from "../components/HomePage-Components/KaryaCard";
import UserLists from "../components/HomePage-Components/UserList";
import Header from "../components/Header";
import { useRouter } from "next/dist/client/router";

export default function Home() {
  const dispatch = useDispatch();
  const allProductsData = useSelector((state) => state.Homes);
  const { loading, error, homes } = allProductsData;
  const router = useRouter();
  // LOAD DATA
  useEffect(() => {
    dispatch(getHomepage());
  }, []);

  return (
    <div>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/boxicons@latest/css/boxicons.min.css"
        />
      </Head>

      <Header />

      <main>
        <KaryaCard
          ProductData={homes.RencentProduct}
          loading={loading}
          error={error}
        />

        <UserLists UserData={homes.Users} loading={loading} error={error} />
      </main>
    </div>
  );
}
