import Head from "next/head";
import Image from "next/image";
import { useEffect } from "react";
import { useDispatch, useSelector } from "react-redux";
import { getHomepage } from "../redux/action/homepageAction";
import styles from "../styles/Home.module.css";
import KaryaCard from "./components/HomePage-Components/KaryaCard";
import UserLists from "./components/HomePage-Components/UserList";
// import "../js/main.js";

export default function Home() {
  const dispatch = useDispatch();
  const allProductsData = useSelector((state) => state.Homes);
  const { loading, error, homes } = allProductsData;

  // LOAD DATA
  useEffect(() => {
    dispatch(getHomepage());
  }, []);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/boxicons@latest/css/boxicons.min.css"
        />
      </Head>

      <header className="header" id="header">
        <nav className="nav container">
          <a href="https://nextjs.org">Batiqun</a>
          {/* <input
            id="quick_search"
            className="xs-hide style-2"
            name="quick_search"
            placeholder="search item here..."
            type="text"
          /> */}
          <div className="nav__menu" id="nav-menu">
            <ul className="nav__list">
              <li className="nav__item">
                <a href="#home" className="nav__link active-link">
                  <i className="bx bx-home-alt nav__icon"></i>
                  <span className="nav__name">Home</span>
                </a>
              </li>
              <li className="nav__item">
                <a href="/Leaderboards" className="nav__link">
                  <i className="bx bx-bar-chart-alt-2 nav__icon"></i>
                  <span className="nav__item">Leaderboards</span>
                </a>
              </li>
              <li className="nav__item">
              <a href="/Profile" className="nav__link">
                  <i className="bx bx-user nav__icon"></i>
                  <span className="nav__item">Profile</span>
                </a>
              </li>
            </ul>
          </div>
        </nav>
      </header>

      <main>
        <KaryaCard ProductData={homes.RencentProduct} loading={loading} error={error}/>

        <UserLists UserData={homes.Users} loading={loading} error={error}/>
      </main>
    </div>
  );
}
