export default function Login(){
return(
    <div className="container-fluid bg-login">
      <title>Login</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/icon.png" />
      
      <div className="main-content">
        <div className="container mt-5 pb-5">
          <div className="row justify-content-center" style={{ marginTop: "10%", marginBottom:"6.8%" }}>
            <div className="col-lg-5 col-md-7">
              <div className="border-0 mb-0">
                <div className="bg-card card-header pb-5">
                <div className="card-body px-lg-5 py-lg-5">
                  <div className="text-center text-muted mb-4">
                    <img className="img-login" src="logo.png"/>
                    <h4 className="textnih">Login With Your Wallet</h4>
                  </div>
                  <div className="text-center">
                    <button type="button" 
                    // onClick={metamaskAuth} 
                    className="btnConnect"> 
                    <img src="image5.png"></img>Connect with Metamask</button>
                  </div>
                </div>
              </div>
            </div>
            </div>
          </div>
        </div>
      </div>
      </div>
    )
}