import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../../styles/Home.module.css";
import { getLeaderboards } from "../../redux/action/leaderboardAction";
import { useEffect, useState } from "react";
import { useDispatch, useSelector } from "react-redux";
import LeaderboardTable from "../../components/LeaderboardComponent/LeaderboardTable";
import Header from "../../components/Header";
// import "../js/main.js";

export default function Home() {
  const dispatch = useDispatch();
  const allLeaderboardsData = useSelector((state) => state.Leaderboards);
  const { loading, error, leaderboards } = allLeaderboardsData;

  useEffect(() => {
    dispatch(getLeaderboards());
  }, []);

  return (
    <div>
      <Head>
        <title>Leaderboards</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/boxicons@latest/css/boxicons.min.css"
        />
      </Head>

      <Header />

      <main>
        <div className="overflow-x-auto">
          <div className="min-w-screen max-w-screen mt-16 flex items-center 
          justify-center font-sans overflow-hidden m-10">
            <div className="w-full lg:w-5/6">
              <div className="bg-white shadow-md rounded my-6"></div>
              <LeaderboardTable
                LeaderboardData={leaderboards}
                loading={loading}
                error={error}
              />
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}
