import Head from "next/head";
import Image from "next/image";
import styles from "../../styles/Home.module.css";
// import "../js/main.js";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Product</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/boxicons@latest/css/boxicons.min.css"
        />
      </Head>

      <header className="header" id="header">
        <nav className="nav container">
          <a href="https://nextjs.org">NFT Browse</a>
          {/* <input
            id="quick_search"
            className="xs-hide style-2"
            name="quick_search"
            placeholder="search item here..."
            type="text"
          /> */}
          <div className="nav__menu" id="nav-menu">
            <ul className="nav__list">
              <li className="nav__item">
                <a href="" className="nav__link">
                  <i className="bx bx-home-alt nav__icon"></i>
                  <span className="nav__name">Home</span>
                </a>
              </li>
              <li className="nav__item">
                <a href="#leaderboards" className="nav__link active-link">
                  <i className="bx bx-bar-chart-alt-2 nav__icon"></i>
                  <span className="nav__item">Leaderboards</span>
                </a>
              </li>
              <li className="nav__item">
                <a href="/Profile" className="nav__link">
                  <i className="bx bx-user nav__icon"></i>
                  <span className="nav__item">Profile</span>
                </a>
              </li>
            </ul>
          </div>
        </nav>
      </header>

      <main>
        <section className="container section section__height">
          <div id="profile">
            <div className="flex">
              <div className="itemBoards">
                <img src="profile.jpg" alt="" />

                <div className="info">
                  <h3 className="name text-dark">Deni</h3>
                </div>
              </div>
              <div className="itemBoards">33333</div>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
