import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../../styles/Home.module.css";
import { getLeaderboards } from "../../redux/action/leaderboardAction";
import { useEffect, useState } from "react";
import { useDispatch, useSelector } from "react-redux";
import LeaderboardTable from "../../components/LeaderboardComponent/LeaderboardTable";
// import "../js/main.js";

export default function Home() {
  const dispatch = useDispatch();
  const allLeaderboardsData = useSelector((state) => state.Leaderboards);
  const { loading, error, leaderboards } = allLeaderboardsData;

  useEffect(() => {
    dispatch(getLeaderboards());
  }, []);

  return (
    <div>
      <Head>
        <title>Leaderboards</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/boxicons@latest/css/boxicons.min.css"
        />
      </Head>

      <header className="header" id="header">
        <nav className="nav container">
          <a href="https://nextjs.org">Batiqun</a>
          {/* <input
            id="quick_search"
            className="xs-hide style-2"
            name="quick_search"
            placeholder="search item here..."
            type="text"
          /> */}
          <div className="nav__menu" id="nav-menu">
            <ul className="nav__list">
              <li className="nav__item">
                <Link href="/">
                  <a className="nav__link">
                    <i className="bx bx-home-alt nav__icon"></i>
                    <span className="nav__name">Home</span>
                  </a>
                </Link>
              </li>
              <li className="nav__item">
                <Link href="/Leaderboards">
                  <a className="nav__link active-link">
                    <i className="bx bx-bar-chart-alt-2 nav__icon"></i>
                    <span className="nav__item">Leaderboards</span>
                  </a>
                </Link>
              </li>
              <li className="nav__item">
                <Link href="/Profile">
                  <a className="nav__link">
                    <i className="bx bx-user nav__icon"></i>
                    <span className="nav__item">Profile</span>
                  </a>
                </Link>
              </li>
            </ul>
          </div>
        </nav>
      </header>

      <main>
        <div className="overflow-x-auto">
          <div className="min-w-screen max-w-screen mt-16 flex items-center justify-center font-sans overflow-hidden m-10">
            <div className="w-full lg:w-5/6">
              <div className="bg-white shadow-md rounded my-6"></div>
              <LeaderboardTable
                LeaderboardData={leaderboards}
                loading={loading}
                error={error}
              />
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}
